server:
  servlet.context-path: /qr-storage-service
  port: 0

qr-storage-service:
  exception:
    print-stack-trace: true
  config:
    kafka:
      server: ${KAFKA_SERVER:localhost:29092}
      group-id: ${spring.application.name}
      enable-auto-commit: true
      generate-qr-code-topic: generateQrCodeTopic


spring:
  application:
    name: qr-storage-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/tinkoff_hw_db}
    username: ${POSTGRES_USERNAME:tfuser}
    password: ${POSTGRES_USERNAME:tfuser}
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 10
        default_schema: qr_storage_service
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        generate_statistics: true
        format_sql: true
        order_updates: true
        order_inserts: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: qr_storage_service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    ru.tfs.spring.hw.qr_storage_service: debug
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: TRACE

---

spring:
  config.activate.on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${TEST_POSTGRES_URL:jdbc:postgresql://localhost:5432/test_tinkoff_hw_db}
    username: ${TEST_POSTGRES_USERNAME:tfuser}
    password: ${TEST_POSTGRES_USERNAME:tfuser}